version: '3'

services:
  db:
    image: 'mongo:3.6'
    volumes:
      - ./.mongodb:/data/db

  react:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WEB_PORT=3000
      - DB_NAME=pm
      - USER_COLLECTION=user
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: >
       ./wait-for-it.sh db:27017 --
       node app.js --mongodb_url=mongodb://docker-01.inforvation.systems:3003
